baseURL = "https://alessandrorota.github.io/"
# title used in the browser tab
title = "Alessandro Rota"
theme = "LoveIt"
languageCode = "en-us"
enableEmoji = true

[params]
version = "0.2.X"

[params.author]
name = "Alessandro Rota"

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"
  [params.header.title]
    logo = ""
    # The header title
    name = "Alessandro Rota"
    pre = ""
    post = ""
    typeit = false

[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/avatar.jpeg"
    title = ""
    subtitle = "Senior Software Engineer based in (mostly) sunny Barcelona ☀️<br>I write about software and whatever topic I find interesting."
    # No typewriter animation for the subtitle
    typeit = false
    social = true
    disclaimer = ""

  [params.home.posts]
    enable = true
    paginate = 6

# Only GitHub, LinkedIn, and Substack
[params.social]
  GitHub = "ale-rota"
  Linkedin = "alessandro-rota-2b1257134"
  Substack = "alerota"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    name = "About"
    url = "/about/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "now"
    name = "Now"
    url = "/now/"
    title = ""
